# Form implementation generated from reading ui file 'artical.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_root(object):
    def setupUi(self, root):
        root.setObjectName("root")
        root.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        root.setEnabled(True)
        root.resize(800, 600)
        root.setMinimumSize(QtCore.QSize(800, 600))
        root.setMaximumSize(QtCore.QSize(800, 600))
        root.setBaseSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=root)
        self.centralwidget.setObjectName("centralwidget")
        self.searchButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(330, 30, 113, 41))
        self.searchButton.setObjectName("searchButton")
        self.pathButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pathButton.setEnabled(True)
        self.pathButton.setGeometry(QtCore.QRect(30, 80, 113, 41))
        self.pathButton.setObjectName("pathButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 90, 441, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.resetButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(450, 30, 113, 41))
        self.resetButton.setObjectName("resetButton")
        self.searchEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.searchEdit.setGeometry(QtCore.QRect(30, 30, 281, 41))
        self.searchEdit.setObjectName("searchEdit")
        self.siteChoose = QtWidgets.QComboBox(parent=self.centralwidget)
        self.siteChoose.setGeometry(QtCore.QRect(580, 30, 161, 41))
        self.siteChoose.setObjectName("siteChoose")
        self.resultListview = QtWidgets.QListWidget(parent=self.centralwidget)
        self.resultListview.setGeometry(QtCore.QRect(30, 130, 400, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultListview.sizePolicy().hasHeightForWidth())
        self.resultListview.setSizePolicy(sizePolicy)
        self.resultListview.setMaximumSize(QtCore.QSize(400, 16777215))
        self.resultListview.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.resultListview.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.resultListview.setResizeMode(QtWidgets.QListView.ResizeMode.Adjust)
        self.resultListview.setObjectName("resultListview")
        self.downloadList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.downloadList.setGeometry(QtCore.QRect(450, 130, 311, 411))
        self.downloadList.setObjectName("downloadList")
        root.setCentralWidget(self.centralwidget)

        self.retranslateUi(root)
        QtCore.QMetaObject.connectSlotsByName(root)

    def retranslateUi(self, root):
        _translate = QtCore.QCoreApplication.translate
        root.setWindowTitle(_translate("root", "小说下载"))
        self.searchButton.setText(_translate("root", "搜索"))
        self.pathButton.setText(_translate("root", "选择保存路径"))
        self.resetButton.setText(_translate("root", "重置"))
        self.searchEdit.setPlaceholderText(_translate("root", "请输入小说名"))
