# Form implementation generated from reading ui file 'download_item.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(310, 60)
        Form.setMaximumSize(QtCore.QSize(16777215, 60))
        self.articleTitle = QtWidgets.QLabel(parent=Form)
        self.articleTitle.setGeometry(QtCore.QRect(10, 10, 231, 16))
        self.articleTitle.setObjectName("articleTitle")
        self.progressBar = QtWidgets.QProgressBar(parent=Form)
        self.progressBar.setGeometry(QtCore.QRect(10, 30, 231, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressLabel = QtWidgets.QLabel(parent=Form)
        self.progressLabel.setGeometry(QtCore.QRect(100, 30, 60, 21))
        self.progressLabel.setObjectName("progressLabel")
        self.actionBtn = QtWidgets.QPushButton(parent=Form)
        self.actionBtn.setGeometry(QtCore.QRect(260, 10, 51, 32))
        self.actionBtn.setText("")
        self.actionBtn.setObjectName("actionBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.articleTitle.setText(_translate("Form", "TextLabel"))
        self.progressLabel.setText(_translate("Form", "TextLabel"))
